---
#Â Environment specific values, override helm_deploy/help-with-prison-visits-asynchronous-worker/values.yaml
replicaCount: 2

env:
  APVS_AUTO_APPROVAL_ENABLED: "true"
  APVS_DWP_BENEFIT_CHECKER_ENABLED: "true"
  APVS_DWP_BENEFIT_CHECKER_URL: "https://laa-benefitchecker-uat.apps.live.cloud-platform.service.justice.gov.uk/lsx/lsc-services/benefitChecker"
  APVS_ZENDESK_ENABLED: "false"
  APVS_ZENDESK_API_URL: "https://test.zendesk.com"
  APVS_EXTERNAL_SERVICE_URL: 'https://help-with-prison-visits-dev.hmpps.service.justice.gov.uk'
  ENVIRONMENT_NAME: dev

generic-prometheus-alerts:
  alertSeverity: help-with-prison-visits-devtest
